export const GET_EMPLOYEE_LOADING = "GET_EMPLOYEE_LOADING"; 
export const GET_EMPLOYEE_SUCCESS = "GET_EMPLOYEE_SUCCESS"; 
export const GET_EMPLOYEE_ERROR = "GET_EMPLOYEE_ERROR";

export const GET_EMPLOYEE_DETAILED_LOADING = "GET_EMPLOYEE_DETAILED_LOADING"; 
export const GET_EMPLOYEE_DETAILED_SUCCESS = "GET_EMPLOYEE_DETAILED_SUCCESS"; 
export const GET_EMPLOYEE_DETAILED_ERROR = "GET_EMPLOYEE_DETAILED_ERROR";

export const NEW_EMPLOYEE_REQUEST = "NEW_EMPLOYEE_REQUEST";
export const NEW_EMPLOYEE_SUCCESS = "NEW_EMPLOYEE_SUCCESS";
export const NEW_EMPLOYEE_RESET = "NEW_EMPLOYEE_RESET";
export const NEW_EMPLOYEE_FAIL = "NEW_EMPLOYEE_FAIL";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_RESET = "UPDATE_EMPLOYEE_RESET";
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL";

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_RESET = "DELETE_EMPLOYEE_RESET";
export const DELETE_EMPLOYEE_FAIL = "DELETE_EMPLOYEE_FAIL";